# Generated by Django 3.1.1 on 2020-09-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Sobrenome', models.CharField(max_length=50)),
                ('Bairrro', models.CharField(max_length=30)),
                ('Cidade', models.CharField(max_length=30)),
            ],
        ),
    ]
