# Generated by Django 3.1.1 on 2020-09-29 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0003_auto_20200929_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volun',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='volun',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='volun',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='volun',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='volun',
            name='valor',
        ),
        migrations.AlterField(
            model_name='volun',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
