# Generated by Django 3.1.1 on 2020-09-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0004_auto_20200929_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volun',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
