# Generated by Django 3.1.1 on 2020-09-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0006_auto_20200930_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='valor',
        ),
        migrations.AddField(
            model_name='produto',
            name='sobrenome',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
