# Generated by Django 3.1.1 on 2020-09-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0007_auto_20200930_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='marca',
        ),
        migrations.AddField(
            model_name='produto',
            name='bairro',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='cidade',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
