# Generated by Django 3.1.1 on 2020-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0009_auto_20200930_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='endereco',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
