# Generated by Django 3.1.1 on 2020-09-30 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0011_produto_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='Instituicao',
        ),
    ]
