# Generated by Django 3.1.1 on 2020-09-30 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0012_remove_produto_instituicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='endereco',
        ),
    ]
