# Generated by Django 3.1.1 on 2020-09-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0013_remove_produto_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='endereco',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo2',
            field=models.CharField(choices=[('bairro ', 'Bairro'), ('cidade', 'Cidade'), ('endereco', 'Endereço')], max_length=100, null=True),
        ),
    ]
