# Generated by Django 3.1.1 on 2020-09-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0014_auto_20200930_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo2',
        ),
    ]
