# Generated by Django 3.1.1 on 2020-10-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0018_auto_20200930_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='resultestado',
            field=models.CharField(choices=[('SP', 'SÃO PAOLO'), ('MG', 'MINAS GERAIS'), ('RJ', 'RIO DE JANEIRO'), ('RS', 'RIO GRANDE DO SUL'), ('BH', 'BAHIA')], max_length=100, null=True),
        ),
    ]
