# Generated by Django 3.1.1 on 2020-10-02 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0019_produto_resultestado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='resultestado',
            new_name='Estado',
        ),
    ]
