# Generated by Django 3.1.1 on 2020-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0020_auto_20201002_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='End',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estado', models.CharField(choices=[('SP', 'SÃO PAOLO'), ('MG', 'MINAS GERAIS'), ('RJ', 'RIO DE JANEIRO'), ('RS', 'RIO GRANDE DO SUL'), ('BH', 'BAHIA')], max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='produto',
            name='Estado',
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('publications', models.ManyToManyField(to='Voluntarios.End')),
            ],
        ),
    ]
