# Generated by Django 3.1.1 on 2020-10-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0021_auto_20201002_1104'),
    ]

    operations = [
        migrations.DeleteModel(
            name='End',
        ),
        migrations.AddField(
            model_name='produto',
            name='Estado',
            field=models.CharField(choices=[('SP', 'SÃO PAOLO'), ('MG', 'MINAS GERAIS'), ('RJ', 'RIO DE JANEIRO'), ('RS', 'RIO GRANDE DO SUL'), ('BH', 'BAHIA')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(to='Voluntarios.Produto'),
        ),
    ]
