# Generated by Django 3.1.1 on 2020-10-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0023_auto_20201002_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estad', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='continente',
        ),
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.DeleteModel(
            name='Cidade',
        ),
        migrations.DeleteModel(
            name='Continente',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
