# Generated by Django 3.1.1 on 2020-10-02 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0025_auto_20201002_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='estado',
            field=models.CharField(choices=[('SP', 'SÃO PAOLO'), ('MG', 'MINAS GERAIS'), ('RJ', 'RIO DE JANEIRO'), ('RS', 'RIO GRANDE DO SUL'), ('BA', 'BAHIA')], max_length=100, null=True),
        ),
    ]
