# Generated by Django 3.1.1 on 2020-10-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0026_estado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='estado',
        ),
    ]
