# Generated by Django 3.1.1 on 2020-10-04 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0027_remove_estado_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endre',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='endre',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='Cidades',
        ),
        migrations.DeleteModel(
            name='endre',
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
