# Generated by Django 3.1.1 on 2020-10-04 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0029_continent_country_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continent',
            old_name='name',
            new_name='casa',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='name',
            new_name='end',
        ),
    ]
