# Generated by Django 3.1.1 on 2020-10-05 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0031_auto_20201004_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='estado',
            name='RESUL',
        ),
        migrations.CreateModel(
            name='Cidade2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OP2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voluntarios.estado')),
                ('RESUL', models.ManyToManyField(to='Voluntarios.Cidade')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='OP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voluntarios.estado'),
        ),
    ]
