# Generated by Django 3.1.1 on 2020-10-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voluntarios', '0032_auto_20201005_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voluntirio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
